sudo: false
language: python
python:
  - '3.5'
  - '3.6'
  - 'pypy'
  - 'pypy3'
# see https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
     - python: 3.7
       dist: xenial
       sudo: true
     - python: 3.8-dev
       dist: xenial
       sudo: true
       allow_failures: true

install:
  - pip install tox-travis

script:
  - make -C libfaketime/vendor/libfaketime
  - tox
