sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
# see https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
     - python: 3.7
       dist: xenial
       sudo: true

install:
  - pip install tox-travis

script:
  - make -C libfaketime/vendor/libfaketime
  - tox
