---
name: tests
on:
  push:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.os }} - python${{ matrix.python }} - ${{ matrix.tz }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-14
          - macos-13
          - macos-12
        python:
          - '3.12'
          - '3.11'
          - '3.10'
          - '3.9'
          - '3.8'
        tz:
          - 'utc'
          - 'cest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip|${{ hashFiles('setup.py') }}|${{ hashFiles('setup.cfg') }}
      - run: pip install tox
      - run: git submodule update --init --force
      - run: |
          git apply --directory libfaketime/vendor/libfaketime libfaketime/vendor/libfaketime.patch
          make -C libfaketime/vendor/libfaketime
      - run: tox -e ${{ matrix.python }}-${{ matrix.tz }}
